name: Safety

on:
  push:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  safety:
    name: "Safety"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.1.1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: |
          pip install pip==20.1.1
          pip --version
      - name: Install Poetry
        run: |
          pip install poetry==1.0.5
          poetry --version
      - name: Install Nox
        run: |
          pip install nox==2020.5.24
          nox --version
      - name: Run Nox Safety Session
        run: |
          nox --force-color -s safety
