name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: "${{ matrix.session }} ${{ matrix.python-version }} / ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.8, os: ubuntu-latest, session: "mypy" }
          - { python-version: 3.7, os: ubuntu-latest, session: "mypy" }
          - { python-version: 3.8, os: ubuntu-latest, session: "pytype" }
          - { python-version: 3.7, os: ubuntu-latest, session: "pytype" }
          - { python-version: 3.8, os: ubuntu-latest, session: "tests" }
          - { python-version: 3.7, os: ubuntu-latest, session: "tests" }
          - { python-version: 3.8, os: windows-latest, session: "tests" }
          - { python-version: 3.8, os: macos-latest, session: "tests" }

    env:
      NOXSESSION: "${{ matrix.session }}-${{ matrix.python-version }}"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.1.1

      - name: Set up Python "${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Upgrade pip
        run: |
          pip install pip==20.1.1
          pip --version
      - name: Install Poetry
        run: |
          pip install poetry==1.0.5
          poetry --version
      - name: Install Nox
        run: |
          pip install nox==2020.5.24
          nox --version
      - name: Run Nox
        run: |
          nox --force-color

      - name: Create coverage report
        if: always() && matrix.session == 'tests'
        run: |
          nox --force-color --session=coverage -- xml
      - name: Upload coverage report
        if: always() && matrix.session == 'tests'
        uses: codecov/codecov-action@v1.0.7
